name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: request-type
    attributes:
      label: Type of Request
      description: What type of feature request is this?
      options:
        - Enhancement to existing feature
        - New devcontainer feature
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: related-feature
    attributes:
      label: Related Feature (if applicable)
      description: If this is an enhancement, which feature does it relate to?
      options:
        - Not applicable
        - gemini-cli
        - biome
        - trufflehog
        - All features
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature in detail
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What's the use case?
      placeholder: |
        I would like to... but currently I can't because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        Describe your ideal solution. For example:
        - Add a new option to devcontainer-feature.json
        - Install additional tools
        - Configure VSCode extensions
    validations:
      required: true

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration
      description: If applicable, provide an example of how this feature would be configured
      placeholder: |
        {
          "features": {
            "ghcr.io/maloma7/devcontainer-features/new-feature:1": {
              "option": "value"
            }
          }
        }
      render: json

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        - Links to similar features in other repositories
        - Screenshots or diagrams
        - Related issues or discussions

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests and didn't find a duplicate
          required: true
        - label: I have read the project documentation
          required: true
